---
title: "ID3"
author: "221810376_Kiran Aldi P. Hasibuan"
date: "11/5/2020"
output: html_document
---

---
title: "C4.5"
author: "221810376_Kiran Aldi P. Hasibuan"
date: "11/5/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(caret)
library(data.tree)
```

```{r}
heart <- read.csv("Heart_Disease_Classification.csv")
str(heart)
```

```{r}
for(i in names(heart)){
  heart[,i]= as.factor(heart[,i])
}
str(heart)
```

```{r}
IsPure <- function(data) {
  length(unique(data[,ncol(data)])) == 1
}
```

```{r}
Entropy <- function( vls ) {
  res <- vls/sum(vls) * log2(vls/sum(vls))
  res[vls == 0] <- 0
  -sum(res)
}
```

```{r}
InformationGain <- function( tble ) {
  tble <- as.data.frame.matrix(tble)
  entropyBefore <- Entropy(colSums(tble))
  s <- rowSums(tble)
  entropyAfter <- sum (s / sum(s) * apply(tble, MARGIN = 1, FUN = Entropy ))
  informationGain <- entropyBefore - entropyAfter
  return (informationGain)
}
```

```{r}
TrainID3 <- function(node, data) {
    
  node$obsCount <- nrow(data)
  
  #if the data-set is pure (e.g. all toxic), then
  if (IsPure(data)) {
    #construct a leaf having the name of the pure feature (e.g. 'toxic')
    child <- node$AddChild(unique(data[,ncol(data)]))
    node$feature <- tail(names(data), 1)
    child$obsCount <- nrow(data)
    child$feature <- ''
  } else {
    #chose the feature with the highest information gain (e.g. 'color')
    ig <- sapply(colnames(data)[-ncol(data)], 
            function(x) InformationGain(
              table(data[,x], data[,ncol(data)])
              )
            )
    feature <- names(ig)[ig == max(ig)][1]
    
    node$feature <- feature
    
    #take the subset of the data-set having that feature value
    childObs <- split(data[,!(names(data) %in% feature)], data[,feature], drop = TRUE)
    
    for(i in 1:length(childObs)) {
      #construct a child having the name of that feature value (e.g. 'red')
      child <- node$AddChild(names(childObs)[i])
      
      #call the algorithm recursively on the child and the subset      
      TrainID3(child, childObs[[i]])
    }
    
  }
  
  

}
```

```{r}
Predict <- function(tree, features) {
  if (tree$children[[1]]$isLeaf) return (tree$children[[1]]$name)
  child <- tree$children[[features[[tree$feature]]]]
  return ( Predict(child, features))
}
```

```{r}
tree <- Node$new("heart")
fit <- TrainID3(tree, heart)
print(tree, "feature", "obsCount")
```

```{r}
Predict(tree, c(age = 55, 
                sex = 0,
                chol = 150, 
                fbs = 1,
                exang = 1,
                slope = 2)
        )
```

